version: '3.8'

services:
  #cookhub-web-admin:
  #  env_file: .env
  #  build:
  #    context: ./../cookhub-admin-web
  #  container_name: cookhub-web-admin
  #  networks:
  #    - cookhub-dev
  #  ports:
  #    - 5000:5000

  cookhub-rest-server:
    depends_on:
      - cookhub-db
      - cookhub-redis
    env_file: .env
    build:
      context: .
    container_name: cookhub-rest-server
    hostname: cookhub-rest-server
    networks:
      - cookhub-dev
    ports:
      - 80:8080
    deploy:
      restart_policy:
        condition: on-failure

  cookhub-db:
    image: postgres:latest
    container_name: cookhub-db
    env_file: .env
    hostname: db
    networks:
      cookhub-dev:
        aliases:
          - database
    ports:
      - 5432:5432
      - 8080:8080
    volumes:
      - ./db/startup_scripts:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    #command: start-single-node --insecure

  cookhub-migrate:
    container_name: cookhub-migrate
    deploy:
      restart_policy:   
        condition: on-failure   
        max_attempts: 3
    image: migrate/migrate
    depends_on:
      - cookhub-db
    env_file:
      - .env
    volumes:
      - ./db/migrations:/database
    command: 
      [ "-path", "/database", "-database", "${MIGRATION_DB_URL}", "up"]
      #[ "-path", "/database", "-database", "${MIGRATION_DB_URL}", "down", "-all"] #- to drop
      #[ "-path", "/database", "-database", "${MIGRATION_DB_URL}", "force", "1"] #- migrate to specific version
    networks:
      - cookhub-dev


  cookhub-redis:
    image: redis
    container_name: cookhub-redis
    hostname: cookhub-redis
    networks:
      cookhub-dev:
        aliases:
          - cookhub-redis
    ports:
      - 6379:6379

networks:
  cookhub-dev:
    driver: bridge
