
--SET NAMES 'utf8';

INSERT INTO onboardings (title, image_url) VALUES ('Удобный поиск и фильтрация', 'https://yaroslavs-imac.local:80/static/onboarding/1.jpg'), ('Сохраняйте рецепты в избранное, создавайте новые и делитесь', 'https://yaroslavs-imac.local:80/static/onboarding/2.jpg'), ('Сканируйте холодильник и проверяйте наличие и срок годности продуктов', 'https://yaroslavs-imac.local:80/static/onboarding/3.jpg');
INSERT INTO users (id, name, image_url) VALUES ('WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Дмитрий Возников', 'https://yaroslavs-imac.local:80/static/avatars/1.jpg');

INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (1, 'Новогодний очень вкусный салат', 235, 100, 5, 'https://yaroslavs-imac.local:80/static/recipes/salad.jpeg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Например, очень вкусный салат, который готовили народы майя перед проведением жертвоприношений.', 2), (2, 'Тыквенный суп котик мяу мяу', 55, 110, 4, 'https://yaroslavs-imac.local:80/static/recipes/tykv_soup.jpeg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Ну, допустим, мяу.', 2);

INSERT INTO recipe_compilations VALUES (1, 'Аюрведические блюда');
INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (3, 'Кичари', 70, 50, 5, 'https://yaroslavs-imac.local:80/static/recipes/kichari.jpeg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Могучая аюрведическая штука, с имбиря неплохо штырит, рекомендую. На удивление хорошо сочетаются рис и маш, считаю, стоит того, чтобы попробовать.', 2), (4, 'Чечевичные котлеты', 60, 90, 3, 'https://yaroslavs-imac.local:80/static/recipes/chech_kotl.jpeg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Котлеты для правильного питания с неправильным вкусом. Если котлеты, то в них должно быть мясо, но тут только здоровая и полезная чечевица, от которой слегка сводит челюсть. Но это же не остановит тебя в стремлении похудеть?', 2);
INSERT INTO recipe_compilations_recipes VALUES (1, 3, 1), (2, 4, 1);

INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (5, 'Перловый суп с морским вкусом', 160, 80, 5, 'https://yaroslavs-imac.local:80/static/recipes/perl_soup.jpeg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Человек укусил пчелу, и она разбухла. Человек полетел собирать мёд, а пчела пошла на работу. Круговорот человека и пчелы...', 2);
INSERT INTO promo_recipes VALUES (1, 5);

-- Единицы измерения

INSERT INTO units VALUES (1, 'г'), (2, 'мл'), (3, 'шт'), (4, 'ч.л.'), (5, 'ст.л.'), (6, 'по вкусу');

-- ИНГРЕДИЕНТЫ

INSERT INTO ingredients VALUES (1, 'Картофель'), (2, 'Морковь'), (3, 'Вода'), (4, 'Рис'), (5, 'Имбирь');
INSERT INTO ingredients VALUES (6, 'Яйцо'), (7, 'Ветчина'), (8, 'Сыр'), (9, 'Растительное масло'), (10, 'Молоко');
INSERT INTO ingredients VALUES (11, 'Мука пшеничная'), (12, 'Сахар'), (13, 'Сметана'), (14, 'Майонез'), (15, 'Помидор');
INSERT INTO ingredients VALUES (16, 'Соль'), (17, 'Колбаса копченая'), (18, 'Перец черный'), (19, 'Крупа манная'), (20, 'Сосиски');
INSERT INTO ingredients VALUES (21, 'Чеснок'), (22, 'Паприка молотая'), (23, 'Лук репчатый'), (24, 'Филе куриное'), (25, 'Сливки 30%');
INSERT INTO ingredients VALUES (26, 'Грибы шампиньоны'), (27, 'Фарш свино-говяжий'), (28, 'Лук зеленый'), (29, 'Макароны'), (30, 'Крабовые палочки');
INSERT INTO ingredients VALUES (31, 'Масло сливочное'), (32, 'Травы прованские сушеные'), (33, 'Кабачок'), (34, 'Черемша'), (35, 'Помидоры черри');
INSERT INTO ingredients VALUES (36, 'Огурец'), (37, 'Редиска'), (38, 'Лук-порей'), (39, 'Перепелиные яйца');

-- ТЕСТОВЫЕ ДАННЫЕ

INSERT INTO recipes_ingredients VALUES (DEFAULT, 2, 1, 1, 400), (DEFAULT, 2, 2, 1, 300), (DEFAULT, 2, 3, 2, 1500);
INSERT INTO recipes_ingredients VALUES (DEFAULT, 1, 1, 3, 2);
INSERT INTO recipes_ingredients VALUES (DEFAULT, 5, 1, 1, 400), (DEFAULT, 5, 3, 2, 2000), (DEFAULT, 5, 4, 1, 350), (DEFAULT, 5, 5, 3, 2);

INSERT INTO recipe_medias VALUES (2, 'https://static.sobaka.ru/images/image/01/63/21/50/_normal.jpeg?v=1671365310', 1), (2, 'https://ir.ozone.ru/s3/multimedia-m/c1000/6275130526.jpg', 1);
INSERT INTO recipe_medias VALUES (1, 'http://jplayer.org/video/m4v/Finding_Nemo_Teaser.m4v', 2);
INSERT INTO recipe_medias VALUES (5, 'https://www.purina.ru/sites/default/files/styles/nppe_breed_selector_500/public/2020-04/french_bulldog.jpg?itok=CWfOzyGk', 1), (5, 'http://jplayer.org/video/m4v/Incredibles_Teaser_320x144_h264aac.m4v', 2), (5, 'https://www.bethowen.ru/upload/medialibrary/ecc/eccb9676c5dbd1524849166d27627e24.jpg', 1);

INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Картошка', 'Нарежь картоху для парилки', 2), (DEFAULT, 2, 'Варка', 'Закинь вариться, пока не станет мягкой', 2), (DEFAULT, 3, 'Финалочка', 'Произвольно намешай еще чего-нибудь, чтобы было вкусно', 2);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Краткость - сестра таланта, как в свое время писал Антон Павлович Чехов', 'Рецепт с одним пунктом, чтобы был', 4);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Пункт 1', 'Мяу', 5), (DEFAULT, 2, 'Пункт 2', 'Длинный-длинный текст, чтобы проверить многострочное отображение пункта приготовления пищи для поедания и удовлетворения примитивных потребностей организма, продлевающих бытие в этом чудесном мире', 5), (DEFAULT, 3, 'Пункт 3', 'Мяу-мяу', 5);

INSERT INTO recipe_food_values VALUES (DEFAULT, 10, 10, 10, 100, 1), (DEFAULT, 20, 20, 20, 200, 2), (DEFAULT, 50, 150, 10, 150, 3), (DEFAULT, 200, 20, 220, 300, 4), (DEFAULT, 50, 50, 5, 120, 5); 


-- ЗАВТРАКИ

INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (6, 'Яичные конвертики с сыром и ветчиной', 20, 150, 5, 'https://img1.russianfood.com/dycontent/images_upl/379/sm_378723.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Сытное и вкусное блюдо "с изюминкой", которое можно приготовить всего из 3 ингредиентов, - аппетитные, нежные и румяные яичные конвертики с ветчиной и сыром. Отличная альтернатива привычной яичнице для завтрака или перекус на скорую руку. Попробуйте!', 1);
INSERT INTO recipe_medias VALUES (6, 'https://img1.russianfood.com/dycontent/images_upl/379/sm_378677.jpg', 1), (6, 'https://img1.russianfood.com/dycontent/images_upl/379/sm_378681.jpg', 1), (6, 'https://img1.russianfood.com/dycontent/images_upl/379/sm_378723.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 6, 6, 3, 4), (DEFAULT, 6, 7, 1, 130), (DEFAULT, 6, 8, 1, 100), (DEFAULT, 6, 9, 4, 1);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'Подготовьте продукты по списку.', 6), (DEFAULT, 2, 'Натрите ветчину и сыр на мелкой терке', 'В отдельной емкости разбейте яйца и слегка взбейте вилкой.', 6), (DEFAULT, 3, 'Жарка', 'Разогрейте сковорду, смажьте растительным маслом, влейте порцию взбитых яиц и равномерно распределите по сковороде. Жарьте примерно 1-2 минуты.', 6), (DEFAULT, 4, 'Переверните яичный блинчик на другую сторону', 'В центр блинчика выложите немного ветчины и натертого сыра.', 6), (DEFAULT, 5, 'Сверните конвертиком и обжарьте еще 20-30 секунд', 'Повторите процесс с оставшейся яичной массой и начинкой.', 6);
INSERT INTO recipe_food_values VALUES (DEFAULT, 10, 80, 200, 100, 6);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (7, 'Панкейки (американские блинчики)', 10, 250, 4, 'https://img1.russianfood.com/dycontent/images_upl/124/sm_123944.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Мягкие, сладкие, вкусные американские блинчики, которые еще называют панкейки (pancakes), отлично сочетаются с медом', 1);
INSERT INTO recipe_medias VALUES (7, 'https://img1.russianfood.com/dycontent/images_upl/124/sm_123947.jpg', 1), (7, 'https://img1.russianfood.com/dycontent/images_upl/124/sm_123949.jpg', 1), (7, 'https://img1.russianfood.com/dycontent/images_upl/124/sm_123953.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 7, 6, 3, 2), (DEFAULT, 7, 10, 2, 200), (DEFAULT, 7, 11, 5, 10), (DEFAULT, 7, 12, 5, 2);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'Смешайте 2 яйца и 200 мл молока.', 7), (DEFAULT, 2, 'Добавьте 2 ст.л. сахара и ваниль, взбейте до однородности', '', 7), (DEFAULT, 3, 'Добавьте 10 ст. л. муки и разрыхлитель.', 'Тщательно перемешайте. Тесто получится средней густоты.', 7), (DEFAULT, 4, 'Разогрейте сковородку с антипригарным покрытием', 'На сухую сковороду налейте тесто небольшим половником. Накройте крышкой, и жарьте панкейки на среднем огне.', 7), (DEFAULT, 5, 'Жарьте блинчики до румяности с двух сторон', 'Переворачивайте, когда верхняя поверхность панкейков станет пористой, при этом будет еще влажной.', 7);
INSERT INTO recipe_food_values VALUES (DEFAULT, 60, 100, 200, 90, 7);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (8, 'Ленивая пицца на сковороде', 30, 450, 5, 'https://img1.russianfood.com/dycontent/images_upl/370/sm_369564.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Для приготовления ленивой пиццы не нужно месить тесто и разогревать духовку. Вам понадобится совсем немного времени, чтобы приготовить быструю и вкусную пиццу на сковороде.', 1);
INSERT INTO recipe_medias VALUES (8, 'https://img1.russianfood.com/dycontent/images_upl/370/big_369553.jpg', 1), (8, 'https://img1.russianfood.com/dycontent/images_upl/370/sm_369555.jpg', 1), (8, 'https://img1.russianfood.com/dycontent/images_upl/370/sm_369557.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 8, 6, 3, 1), (DEFAULT, 8, 13, 5, 2), (DEFAULT, 8, 14, 5, 2), (DEFAULT, 8, 12, 5, 4), (DEFAULT, 8, 17, 1, 100), (DEFAULT, 8, 8, 1, 80), (DEFAULT, 8, 15, 3, 1), (DEFAULT, 8, 16, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'Колбасу нарезать тонкими ломтиками. Помидор нарезать тонкими дольками. Сыр натереть на тёрке.', 8), (DEFAULT, 2, 'Замешать тесто', 'В миску выложить сметану и майонез, вбить яйцо, посолить и поперчить. Перемешать до однородности. Всыпать всю муку, замесить.', 8), (DEFAULT, 3, 'Выкладываем ингредиенты на сковороду', 'Холодную сковороду (диаметром 20 см) смазать растительным маслом. Выложить тесто, на тесто выложить колбасу, затем помидоры.', 8), (DEFAULT, 4, 'Жарим пиццу', 'Присыпать сверху тёртым сыром. Поставить сковороду на средний огонь, накрыть крышкой и готовить пиццу на сковороде 20 минут.', 8);
INSERT INTO recipe_food_values VALUES (DEFAULT, 80, 150, 250, 200, 8);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (9, 'Манные биточки', 50, 150, 4, 'https://img1.russianfood.com/dycontent/images_upl/616/sm_615936.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Биточки из манной каши (манники) получаются нежными внутри и с румяной корочкой снаружи. Готовить их не намного сложнее, чем сварить манную кашу.', 1);
INSERT INTO recipe_medias VALUES (9, 'https://img1.russianfood.com/dycontent/images_upl/616/big_615937.jpg', 1), (9, 'https://img1.russianfood.com/dycontent/images_upl/616/sm_615940.jpg', 1), (9, 'https://img1.russianfood.com/dycontent/images_upl/616/big_615944.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 9, 10, 2, 500), (DEFAULT, 9, 19, 1, 160), (DEFAULT, 9, 11, 5, 2), (DEFAULT, 9, 6, 5, 1), (DEFAULT, 9, 9, 5, 2), (DEFAULT, 9, 12, 1, 60);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'В кастрюле вскипятите молоко. Непрерывно помешивая молоко венчиком, тонкой струйкой всыпьте манную крупу. Варите кашу около 3 минут, до загустения. Каша должна получиться густой.', 9), (DEFAULT, 2, 'Готовимся к жарке', 'Готовую кашу переложите в миску и оставьте остывать до тёплого состояния. Затем вбейте яйцо, всыпьте сахар, ванилин и маленькую щепотку соли. Перемешайте.', 9), (DEFAULT, 3, 'Формируем биточки', 'Смоченными в воде руками сформируйте из манного "теста" круглую толстенькую лепёшку и обваляйте её в муке. Таким образом сформируйте остальные биточки.', 9), (DEFAULT, 4, 'Жарим биточки', 'Обжарьте биточки на небольшом огне по 3 минуты с каждой стороны, до золотистой корочки.', 9);
INSERT INTO recipe_food_values VALUES (DEFAULT, 100, 170, 300, 100, 9);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (10, 'Каша рисовая', 40, 200, 3, 'https://img1.russianfood.com/dycontent/images_upl/177/sm_176757.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Самый лучший завтрак - это каша. Вкусно и полезно. Для вас на заметку каша рисовая на молоке. Вот рецепт. Так же варятся перловая, пшеничная, овсяная каши.', 1);
INSERT INTO recipe_medias VALUES (10, 'https://img1.russianfood.com/dycontent/images_upl/177/sm_176723.jpg', 1), (10, 'https://img1.russianfood.com/dycontent/images_upl/177/sm_176726.jpg', 1), (10, 'https://img1.russianfood.com/dycontent/images_upl/177/sm_176757.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 10, 4, 1, 220), (DEFAULT, 10, 10, 2, 330), (DEFAULT, 10, 3, 2, 500), (DEFAULT, 10, 12, 1, 25);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'Рис промыть, воду вскипятить.', 7), (DEFAULT, 2, 'Варим рис', 'В кипящую воду всыпать соль, сахар, подготовленный рис. Варить, помешивая, на среднем огне 20 минут.', 10), (DEFAULT, 3, 'Молоко вскипятить', 'Налить горячее молоко в кастрюлю с рисом. Перемешать и продолжить варку риса при слабом кипении еще 20 минут.', 10), (DEFAULT, 4, 'Готово!', 'Молочную рисовую кашу при подаче можно заправить маслом.', 10);
INSERT INTO recipe_food_values VALUES (DEFAULT, 120, 70, 120, 70, 10);

-- ОБЕДЫ (в тестовых рецептах, есть 5 штук, пока можно игнорить)

-- УЖИНЫ

INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (11, 'Картошка, запечённая с сосисками, помидорами и сыром', 65, 700, 5, 'https://img1.russianfood.com/dycontent/images_upl/559/sm_558596.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Простое, но достаточно интересное блюдо - запечённая картошка с сосисками, помидорами и сыром.', 3);
INSERT INTO recipe_medias VALUES (11, 'https://img1.russianfood.com/dycontent/images_upl/559/sm_558595.jpg', 1), (11, 'https://img1.russianfood.com/dycontent/images_upl/559/sm_558601.jpg', 1), (11, 'https://img1.russianfood.com/dycontent/images_upl/559/sm_558606.jpg', 1), (11, 'https://img1.russianfood.com/dycontent/images_upl/559/sm_558596.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 11, 1, 3, 5), (DEFAULT, 11, 20, 3, 4), (DEFAULT, 11, 15, 3, 2), (DEFAULT, 11, 8, 1, 90), (DEFAULT, 11, 14, 1, 100), (DEFAULT, 11, 21, 3, 1), (DEFAULT, 11, 16, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'Включите духовку, пусть разогревается до 190 градусов.', 11), (DEFAULT, 2, 'Нарежьте продукты', 'Очищенный картофель нарежьте кубиками среднего размера, сосиски - кружочками, помидоры - некрупными кубиками.', 11), (DEFAULT, 3, 'Выкладываем на форму.', 'В глубокой миске соедините картофель, сосиски и помидоры. Добавьте майонез, соль, чёрный молотый перец и молотую паприку. Чеснок очистите, мелко нарежьте и тоже отправьте в миску. Перемешайте и распределите по форме.', 11), (DEFAULT, 4, 'Запекаем', 'Поместите форму с заготовкой в предварительно разогретую до 190 градусов духовку на 40 минут, почти до полной готовности картофеля (зависит от сорта и размера кусочков картошки, а также от особенностей вашей духовки).', 11), (DEFAULT, 5, 'Добавляем сыр', 'По истечении времени достаньте форму из духовки. Твёрдый сыр натрите на крупной тёрке и распределите поверх картофеля с сосисками и помидорами. Верните овощи с сосисками и сыром в духовку и запекайте ещё 10 минут.', 11);
INSERT INTO recipe_food_values VALUES (DEFAULT, 50, 150, 450, 400, 11);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (12, 'Жюльен с курицей и грибами', 35, 1200, 5, 'https://img1.russianfood.com/dycontent/images_upl/195/sm_194679.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Очень популярную закуску - жульен (или точнее жюльен) с курицей и грибами, можно приготовить на сковороде, примерно за полчаса, совершенно не напрягая себя приобретением кокотниц и доведением блюда до готовности в духовке.', 3);
INSERT INTO recipe_medias VALUES (12, 'https://img1.russianfood.com/dycontent/images_upl/195/sm_194680.jpg', 1), (12, 'https://img1.russianfood.com/dycontent/images_upl/195/sm_194684.jpg', 1), (12, 'https://img1.russianfood.com/dycontent/images_upl/195/sm_194686.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 12, 24, 1, 400), (DEFAULT, 12, 26, 1, 300), (DEFAULT, 12, 23, 1, 100), (DEFAULT, 12, 25, 2, 200), (DEFAULT, 12, 8, 1, 150), (DEFAULT, 12, 9, 5, 2), (DEFAULT, 12, 16, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'Куриное филе нарежьте небольшими кусочками. Обжарьте на растительном масле несколько минут до полуготовности. Лук мелко нарежьте, добавьте к курице и жарьте куриное филе с луком еще 3-4 минуты.', 12), (DEFAULT, 2, 'Добавляем грибы', 'Шампиньоны крупно нарежьте и добавьте в сковороду. После того, как выпарится влага из грибов, посолите, поперчите и готовьте курицу с луком и грибами еще 5-7 минут, до золотистого цвета.', 12), (DEFAULT, 3, 'Заливаем сливками.', 'Залейте мясо и грибы сливками, немного прогрейте всё вместе.', 12), (DEFAULT, 4, 'Добавляем сыр', 'Сыр натрите на крупной терке и выложите сверху. Выключите огонь и накройте сковороду крышкой. Когда через 3-5 минут сыр расплавится, жюльен с грибами и курицей можно подавать к столу.', 12);
INSERT INTO recipe_food_values VALUES (DEFAULT, 150, 250, 600, 500, 12);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (13, 'Запеканка из картофеля и мясного фарша', 75, 1000, 4, 'https://img1.russianfood.com/dycontent/images_upl/214/sm_213550.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Простой в приготовлении, сытный и вкусный семейный обед или ужин - картофельная запеканка с мясным фаршем.', 3);
INSERT INTO recipe_medias VALUES (13, 'https://img1.russianfood.com/dycontent/images_upl/214/sm_213551.jpg', 1), (13, 'https://img1.russianfood.com/dycontent/images_upl/214/sm_213553.jpg', 1), (13, 'https://img1.russianfood.com/dycontent/images_upl/214/sm_213556.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 13, 1, 1, 700), (DEFAULT, 13, 27, 1, 400), (DEFAULT, 13, 8, 1, 80), (DEFAULT, 13, 28, 3, 4), (DEFAULT, 13, 6, 3, 2), (DEFAULT, 13, 13, 5, 2), (DEFAULT, 13, 18, 6, 0), (DEFAULT, 13, 16, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка картофеля', 'Картофель очистите, вымойте вместе с луком, обсушите. Натрите картофель на крупной терке, образовавшуюся жидкость нужно отжать.', 13), (DEFAULT, 2, 'Выкладываем в форму', 'Половину картофеля выложите в смазанную маслом форму для запекания. На картофель выложите мясной фарш, посолите и поперчите его по вкусу.', 13), (DEFAULT, 3, 'Выкладываем вторую часть продуктов.', 'Нарежьте зеленый лук, посыпьте им фарш. Натрите сыр на крупной терке. Смешайте сыр со второй половиной натертого картофеля, добавьте яйцо (или два). Перемешайте, чуть поперчите и посолите', 13), (DEFAULT, 4, 'Запекаем', 'Выложите картофель с сыром на слой фарша, разровняйте ложкой. Готовьте запеканку из картофеля и мясного фарша в предварительно разогретой до 180 градусов духовке примерно 1 час.', 13);
INSERT INTO recipe_food_values VALUES (DEFAULT, 120, 200, 500, 300, 13);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (14, 'Куриные котлеты по-французски', 30, 500, 3, 'https://img1.russianfood.com/dycontent/images_upl/117/sm_116992.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Куриные котлеты по-французски (другие названия - котлеты по-министерски, по-албански) очень нежные и сочные, просто тают во рту.', 3);
INSERT INTO recipe_medias VALUES (14, 'https://img1.russianfood.com/dycontent/images_upl/117/sm_116992.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 14, 24, 1, 500), (DEFAULT, 14, 6, 3, 2), (DEFAULT, 14, 14, 5, 2), (DEFAULT, 14, 11, 5, 2), (DEFAULT, 14, 23, 3, 1), (DEFAULT, 14, 16, 6, 0), (DEFAULT, 14, 18, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Нарезаем продукты', 'Нарезаем лук и куриное филе квадратиками.', 14), (DEFAULT, 2, 'Смешиваем лук и филе', 'Солим, перчим.', 14), (DEFAULT, 3, 'Готовимся к жарке', 'Добавляем сначала аккуратно одно яйцо. (Если будет не хватать по консистенции, то добавим второе.) Добавляем майонез. Высыпаем муку, перемешиваем массу.', 14), (DEFAULT, 4, 'Жарим', 'Столовой ложкой выкладываем котлеты на сковородку. Обжариваем с каждой стороны по 3-4 минуты.', 14);
INSERT INTO recipe_food_values VALUES (DEFAULT, 150, 250, 300, 200, 14);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (15, 'Макароны с крабовыми палочками, сметаной и чесноком', 25, 500, 5, 'https://img1.russianfood.com/dycontent/images_upl/552/sm_551637.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Ещё один рецепт в копилку простых, но вкусных блюд. Макароны с крабовыми палочками, сметаной и чесноком – это очень вкусно, сытно и быстро! Крабовые палочки и сметана обеспечивают нежный вкус, а чеснок придаёт пикантность и аппетитный аромат.', 3);
INSERT INTO recipe_medias VALUES (15, 'https://img1.russianfood.com/dycontent/images_upl/552/sm_551638.jpg', 1), (15, 'https://img1.russianfood.com/dycontent/images_upl/552/sm_551639.jpg', 1), (15, 'https://img1.russianfood.com/dycontent/images_upl/552/sm_551643.jpg', 1), (15, 'https://img1.russianfood.com/dycontent/images_upl/552/sm_551645.jpg', 1), (15, 'https://img1.russianfood.com/dycontent/images_upl/552/sm_551637.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 15, 29, 1, 100), (DEFAULT, 15, 30, 1, 100), (DEFAULT, 15, 21, 3, 1), (DEFAULT, 15, 31, 1, 10), (DEFAULT, 15, 8, 1, 10), (DEFAULT, 15, 13, 5, 2), (DEFAULT, 15, 11, 4, 1), (DEFAULT, 15, 32, 6, 0), (DEFAULT, 15, 16, 6, 0), (DEFAULT, 15, 18, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Варим макароны', 'В небольшую кастрюлю наливаем воду, добавляем 1 щепотку соли, доводим до кипения. Опускаем макароны в кипящую воду, перемешиваем и варим, периодически помешивая, примерно 8-10 минут или согласно инструкции на упаковке, до мягкости.', 15), (DEFAULT, 2, 'Нарезаем продукты', 'Нарезаем крабовые палочки кружочками. Чеснок очищаем и нарезаем мелкими кусочками.', 15), (DEFAULT, 3, 'Готовим в сковороде', 'В сковороде растапливаем сливочное масло. Чеснок обжариваем на сливочном масле 1-2 минуты. Всыпаем муку, добавляем соль, перец и прованские травы. Быстро перемешиваем. Добавляем сметану, крабовые палочки, перемешиваем и готовим 2 минуты', 15), (DEFAULT, 4, 'Добавляем макароны', 'Добавляем отваренные макароны, перемешиваем и прогреваем 2 минуты.', 15), (DEFAULT, 5, 'Добавляем сыр', 'Сыр натираем на мелкой тёрке. Подаём блюдо в горячем виде, посыпав сверху натёртым сыром.', 15);
INSERT INTO recipe_food_values VALUES (DEFAULT, 40, 160, 400, 300, 15);

-- ПЕРЕКУСЫ

INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (16, 'Помидоры на сковороде с чесноком жареные', 15, 100, 5, 'https://static.1000.menu/res/640/img/content-v2/dd/01/40005/pomidory-na-skovorode-s-chesnokom-jarenye_1571774831_13_max.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Легкая и быстрая в приготовлении овощная закуска! Жареные помидоры с чесноком – очень простое в приготовлении и по составу, но в то же время вкусное блюдо, которое может выступить не только легким перекусом, но и отличным вариантом для завтрака или ужина, гарниром к мясу или дополнением к гарниру.', 4);
INSERT INTO recipe_medias VALUES (16, 'https://static.1000.menu/res/380/img/content-v2/dd/01/40005/pomidory-na-skovorode-s-chesnokom-jarenye_1571772067_1_max.jpg', 1), (16, 'https://static.1000.menu/res/380/img/content-v2/dd/01/40005/pomidory-na-skovorode-s-chesnokom-jarenye_1571772067_4_max.jpg', 1), (16, 'https://static.1000.menu/res/380/img/content-v2/dd/01/40005/pomidory-na-skovorode-s-chesnokom-jarenye_1571772067_6_max.jpg', 1), (16, 'https://static.1000.menu/res/640/img/content-v2/dd/01/40005/pomidory-na-skovorode-s-chesnokom-jarenye_1571774831_13_max.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 16, 15, 3, 5), (DEFAULT, 16, 21, 3, 2), (DEFAULT, 16, 9, 5, 1), (DEFAULT, 16, 16, 6, 0), (DEFAULT, 16, 18, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'Помидоры моем, даем воде стечь или просушиваем бумажными полотенцами. Нарезаем томаты на кружочки толщиной около одного сантиметра. На сковороду наливаем растительное масло. Хорошо разогреваем его, выкладываем на разогретое масло кружочки помидоров.', 16), (DEFAULT, 2, 'Жарим помидоры', 'Убавляем огонь до среднего, жарим помидоры с одной стороны около двух минут, не накрывая сковороду крышкой, в противном случае помидоры пустят сок и получится томатная паста.', 16), (DEFAULT, 3, 'Режем и добавляем чеснок.', 'Добавляем приготовленный чеснок, соль и черный молотый перец по вкусу. Держим овощи на огне еще 3-4 минуты, на пару минут сковороду можно прикрыть крышкой, чтобы чеснок пустил сок и сделал масло более ароматным.', 16), (DEFAULT, 4, 'Завершаем', 'крышку на сковороде долго не держим, чтобы помидоры не начали «расползаться». Аккуратно смещаем на сковороде помидоры с чесноком, чтобы помидоры впитали в себя ароматное масло. Выключаем огонь.', 16);
INSERT INTO recipe_food_values VALUES (DEFAULT, 10, 80, 50, 120, 16);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (17, 'Кабачки в муке на сковороде', 30, 140, 4, 'https://static.1000.menu/res/640/img/content-v2/3e/56/35696/kabachki-v-muke-na-skovorode_1615649164_11_max.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'На скорую руку, очень просто, очень вкусно, на каждый день! Кабачки в муке на сковороде можно готовить на перекус, на закуску и на гарнир. Они подходят для завтрака и для ужина, хорошо сочетаются с чесноком, сыром, помидорами, другими овощами и мясом. Проще простого!', 4);
INSERT INTO recipe_medias VALUES (17, 'https://static.1000.menu/res/380/img/content/35696/kabachki-v-muke-na-skovorode_1560189078_1_max.jpg', 1), (17, 'https://static.1000.menu/res/380/img/content/35696/kabachki-v-muke-na-skovorode_1560189078_3_max.jpg', 1), (17, 'https://static.1000.menu/res/380/img/content/35696/kabachki-v-muke-na-skovorode_1560189078_4_max.jpg', 1), (17, 'https://static.1000.menu/res/380/img/content/35696/kabachki-v-muke-na-skovorode_1560189078_7_max.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 17, 33, 1, 300), (DEFAULT, 17, 9, 5, 2), (DEFAULT, 17, 11, 1, 50), (DEFAULT, 17, 16, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'Кабачки вымойте, обсушите. Если кожица толстая и жесткая, срежьте ее. Кабачки нарежьте кружочками толщиной около 1 см. Кабачки посолите, перемешайте и оставьте на 10-15 минут. Выделившийся сок слейте.', 17), (DEFAULT, 2, 'Панируем в просеянной муке', 'Кабачки с двух сторон запанируйте в муке. Я просто добавляю нарезанные кружочки кабачков в тарелку с мукой и перемешиваю все руками. Но вы можете обваливать каждый кусочек по отдельности.', 17), (DEFAULT, 3, 'Жарим', 'В сковороде разогрейте растительное масло и обжарьте на нем кабачки с двух сторон до появления золотистой корочки.', 17);
INSERT INTO recipe_food_values VALUES (DEFAULT, 20, 90, 120, 100, 17);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (18, 'Салат из черемши', 15, 66, 4, 'https://static.1000.menu/res/640/img/content-v2/83/54/2821/salat-iz-cheremshi_1578940100_10_max.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Полезный и богатый белком салатик не оставит вас голодными!', 4);
INSERT INTO recipe_medias VALUES (18, 'https://static.1000.menu/res/380/img/content/2821/novji-salat-2010_max_8114.jpg', 1), (18, 'https://static.1000.menu/res/380/img/content/2821/novji-salat-2010_max_919.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 18, 34, 3, 10), (DEFAULT, 18, 35, 3, 10), (DEFAULT, 18, 36, 1, 200), (DEFAULT, 18, 37, 1, 150), (DEFAULT, 18, 38, 1, 150), (DEFAULT, 18, 6, 3, 3), (DEFAULT, 18, 16, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Подготовка', 'Измельчите лук. Редис вымойте, отрежьте кончики с двух сторон, разрежьте на 2 части и нарежьте полукружочками. Помидоры вымойте и нарежьте на четыре части. Огурцы вымойте и нарежьте тонкими кружочками.', 18), (DEFAULT, 2, 'Готовим салат', 'В салатнице перемешайте черемшу с помидорами, огурцами, редисом и луком. Все это – подсолите по вкусу. Для оформления подачи нам также потребуются отваренные вкрутую яйца.', 18);
INSERT INTO recipe_food_values VALUES (DEFAULT, 30, 50, 40, 90, 18);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (19, 'Салат из помидоров с огурцом и луком', 15, 150, 5, 'https://static.1000.menu/res/640/img/content-v2/dc/1d/36406/salat-iz-pomidorov-s-ogurcom-i-lukom_1613988871_7_max.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'На скорую руку, очень вкусный, свежий, летний, яркий! Салат из помидоров с огурцом и луком без майонеза освежит любой стол. Его можно подавать в дополнение к мясным, рыбным блюдам или сам по себе.', 4);
INSERT INTO recipe_medias VALUES (19, 'https://static.1000.menu/res/380/img/content/36406/salat-iz-pomidorov-s-ogurcom-i-lukom_1562163876_1_max.jpg', 1), (19, 'https://static.1000.menu/res/380/img/content/36406/salat-iz-pomidorov-s-ogurcom-i-lukom_1562163876_3_max.jpg', 1), (19, 'https://static.1000.menu/res/380/img/content/36406/salat-iz-pomidorov-s-ogurcom-i-lukom_1562165388_5_max.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 19, 36, 3, 2), (DEFAULT, 19, 15, 3, 2), (DEFAULT, 19, 23, 3, 1), (DEFAULT, 19, 9, 5, 2), (DEFAULT, 19, 16, 4, 1);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Нарезаем овощи', 'Огурцы нарежьте ломтиками небольшого размера и переложите в миску для салата. Помидоры нарежьте ломтиками примерно такого же размера и формы, как огурцы. Добавьте измельченные помидоры в миску к огурцам.', 19), (DEFAULT, 2, 'Добавляем лук', 'Лук почистите и нарежьте тонкими полукольцами или четверть кольцами. Добавьте к измельченным овощам, разделив отдельные ломтики лука руками. Остается только заправить салат из помидоров с огурцом и луком растительным маслом, посолить по вкусу.', 19);
INSERT INTO recipe_food_values VALUES (DEFAULT, 10, 70, 40, 70, 19);


INSERT INTO recipes (id, title, cooktime, calories, rating, title_image_url, author_id, description, recipe_type) VALUES (20, 'Салат из редиски с огурцом', 15, 50, 4, 'https://static.1000.menu/res/640/img/content-v2/2a/58/7774/salat-iz-rediski-s-ogurcom_1679159187_3_max.jpg', 'WPLfq0KRbMg7ziylPtR3d2Wditr1', 'Легкий, полезный, недорогой, самый лучший! Салат из редиски с огурцом — блюдо, которое чаще всего появляется на столе весной, в период первых свежих овощей.', 4);
INSERT INTO recipe_medias VALUES (20, 'https://static.1000.menu/res/380/img/content-v2/2a/58/7774/salat-iz-redisa-i-svezhego-ogurtsa_1583996668_1_max.jpg', 1), (20, 'https://static.1000.menu/res/380/img/content-v2/2a/58/7774/salat-iz-redisa-i-svezhego-ogurtsa_1583996668_3_max.jpg', 1), (20, 'https://static.1000.menu/res/380/img/content-v2/2a/58/7774/salat-iz-redisa-i-svezhego-ogurtsa_1583996668_5_max.jpg', 1); 
INSERT INTO recipes_ingredients VALUES (DEFAULT, 20, 37, 1, 300), (DEFAULT, 20, 36, 3, 1), (DEFAULT, 20, 28, 1, 20), (DEFAULT, 20, 13, 5, 2), (DEFAULT, 20, 16, 6, 0);
INSERT INTO recipes_steps VALUES (DEFAULT, 1, 'Нарезаем овощи', 'Подготовьте чашу для приготовления салата. Нарежьте в неё огурец. Достаточно разрезать в длину на 2 или 4 части, а затем просто порезать его на кусочки. Точно так же, четвертинками, нарежьте и редис.', 20), (DEFAULT, 2, 'Заправляем', 'Следом добавьте немного сметаны. По вкусу посолите салат. В качестве заправки можно использовать не только сметану. Попробуйте заменить её натуральным йогуртом или оливковым маслом.', 20);
INSERT INTO recipe_food_values VALUES (DEFAULT, 10, 30, 30, 60, 20);

INSERT INTO recipe_compilations VALUES (2, 'Рекомендовано для вас');
INSERT INTO recipe_compilations_recipes VALUES (3, 14, 2), (4, 20, 2), (5, 10, 2), (6, 15, 2);